// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTag'](arg1, arg2, arg3);
}

export function GetImages(arg1) {
  return window['go']['main']['App']['GetImages'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenInFileExplorer(arg1) {
  return window['go']['main']['App']['OpenInFileExplorer'](arg1);
}

export function RemoveTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveTag'](arg1, arg2, arg3);
}

export function SetFolderPath() {
  return window['go']['main']['App']['SetFolderPath']();
}
