// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddImageByLink(arg1:string,arg2:string,arg3:string):Promise<main.Images>;

export function AddTag(arg1:string,arg2:string,arg3:string):Promise<main.Images>;

export function DeleteImageWithLink(arg1:string,arg2:string):Promise<main.Images>;

export function GetImages(arg1:string):Promise<main.Images>;

export function Greet(arg1:string):Promise<string>;

export function OpenInFileExplorer(arg1:string):Promise<void>;

export function RemoveTag(arg1:string,arg2:string,arg3:string):Promise<main.Images>;

export function SetFolderPath():Promise<string>;
